version: "3.8"

networks:
  app-tier:
    driver: bridge

services:
  db:
    container_name: db
    image: mysql:latest
    command: --default-authentication-plugin=caching_sha2_password
    restart: unless-stopped
    expose:
      - "3306"
    networks:
      - app-tier

    environment:
      - MYSQL_DATABASE=express-ts
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=ok
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_ROOT_HOST=localhost # Allow connections from any host

    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    # command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-tier
    environment:
      - MYSQL_DATABASE=express-ts
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
volumes:
  my-db:
